### ISSUE TITLE
ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down 

### ISSUE THREAD

**Issue by albjeremias** [IsraelHikingMap/graphhopper-docker-image-push#30]
````
graphhopper_1  | 2022-12-29 18:14:20.276 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - car4wd - Marked 1122309 subnetworks (biggest: 345 edges) -> 6 components(s) remain (smallest: 458, biggest: 3619716 edges), total marked edges: 22334, took: 0.72206014s
graphhopper_1  | 2022-12-29 18:14:24.235 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - hike - Found 151280 subnetworks (139562 single edges and 11718 components with more than one edge, total nodes: 4916570), took: 3.9585626s
graphhopper_1  | 2022-12-29 18:14:24.533 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - hike - Marked 151272 subnetworks (biggest: 370 edges) -> 8 components(s) remain (smallest: 586, biggest: 4499766 edges), total marked edges: 39918, took: 0.29780337s
graphhopper_1  | 2022-12-29 18:14:28.543 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - mtb - Found 467104 subnetworks (454838 single edges and 12266 components with more than one edge, total nodes: 4916570), took: 4.0100274s
graphhopper_1  | 2022-12-29 18:14:28.618 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - mtb - Marked 467096 subnetworks (biggest: 370 edges) -> 8 components(s) remain (smallest: 446, biggest: 4199321 edges), total marked edges: 46872, took: 0.07496776s
graphhopper_1  | 2022-12-29 18:14:28.618 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - Finished finding and marking subnetworks for 3 jobs, took: 14.980878s, totalMB:1024, usedMB:580
graphhopper_1  | 2022-12-29 18:14:28.620 [main] INFO  com.graphhopper.GraphHopper - nodes: 1 878 423, edges: 2 458 285
graphhopper_1  | 2022-12-29 18:14:28.861 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
graphhopper_1  | java.lang.IllegalStateException: location index was opened with incorrect graph: 3746312 vs. 3746618
graphhopper_1  |        at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:136)
graphhopper_1  |        at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1190)
graphhopper_1  |        at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1205)
graphhopper_1  |        at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:1108)
graphhopper_1  |        at com.graphhopper.GraphHopper.process(GraphHopper.java:806)
graphhopper_1  |        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:756)
graphhopper_1  |        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:104)
graphhopper_1  |        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
graphhopper_1  |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
graphhopper_1  |        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
graphhopper_1  |        at org.eclipse.jetty.server.Server.start(Server.java:423)
graphhopper_1  |        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
graphhopper_1  |        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
graphhopper_1  |        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
graphhopper_1  |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
graphhopper_1  |        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
graphhopper_1  |        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:60)
graphhopper_1  |        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
graphhopper_1  |        at io.dropwizard.cli.Cli.run(Cli.java:78)
graphhopper_1  |        at io.dropwizard.Application.run(Application.java:94)
graphhopper_1  |        at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)
graphhopper_1  | java.lang.IllegalStateException: location index was opened with incorrect graph: 3746312 vs. 3746618
graphhopper_1  |        at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:136)
graphhopper_1  |        at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1190)
graphhopper_1  |        at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1205)
graphhopper_1  |        at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:1108)
graphhopper_1  |        at com.graphhopper.GraphHopper.process(GraphHopper.java:806)
graphhopper_1  |        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:756)
graphhopper_1  |        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:104)
graphhopper_1  |        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
graphhopper_1  |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
graphhopper_1  |        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
graphhopper_1  |        at org.eclipse.jetty.server.Server.start(Server.java:423)
graphhopper_1  |        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
graphhopper_1  |        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
graphhopper_1  |        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
graphhopper_1  |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
graphhopper_1  |        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
graphhopper_1  |        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:60)
graphhopper_1  |        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
graphhopper_1  |        at io.dropwizard.cli.Cli.run(Cli.java:78)
graphhopper_1  |        at io.dropwizard.Application.run(Application.java:94)
graphhopper_1  |        at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)
helpbuttonsorg_graphhopper_1 exited with code 1
` ``

docker-compose.yml
```
  graphhopper:
    image: israelhikingmap/graphhopper:6.2
    ports:
      - "8989:8989"
    volumes:
      - "./graphhopper:/gh-data:ro"
      - "./graphhopper-data:/data:rw"
    entrypoint: bash -c "chmod +x ./graphhopper.sh && ls /gh-data/ && ./graphhopper.sh --host 0.0.0.0 -i /gh-data/portugal-latest.osm.pbf -o /data/default-gh/ -c /gh-data/gh-config.yml"
    environment:
      - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=1024m
````

I expect the server to run, when i do
` curl http://localhost:8989`
but it crashes, memory issues maybe? I already put to 1024m im using the pbf of portugal got from: 
https://download.geofabrik.de/europe/portugal-latest.osm.pbf

**Comment by HarelM** [comment]
The volumes definitions are weird.
6.2 doesn't need chmod.
Use the following script to create a graph:
https://github.com/IsraelHikingMap/Site/blob/main/gh-update.ps1
And the following docker-compose for configuration.
https://github.com/IsraelHikingMap/Site/blob/d267210bb73f2c3af90523684e606ee57e583b7a/docker-compose.yml#L26
Only after running the `gh-update.ps1` run `docker-copmose up graphhopper`

**Comment by albjeremias** [comment]
I'm sorry still trying to understand the ecosystem, ill try to write an article about all my steps :)

https://github.com/graphhopper/graphhopper/issues/1921

**Comment by albjeremias** [comment]
added debugging logfiles.. could not put it up and running yet.! its a problem of memory. do u have any tweak on docker to use more memory?

**Comment by HarelM** [comment]
Looks like your env variable name is wrong - the container is using 1 Gb while you wanted it to use 12 Gb.
See here:
https://github.com/IsraelHikingMap/Site/blob/d267210bb73f2c3af90523684e606ee57e583b7a/gh-update.ps1#L4
It should be `JAVA_OPTS` and not `JVM_OPTS`.

**Comment by albjeremias** [comment]
yay, made it work... tweaked a bit the config file.. until it worked..  

here my gh-config.yml
```
graphhopper:
  datareader.file: ""  graph.location: graph-cache
      vehicle: hike
      weighting: short_fastest
  profiles_ch:    - profile: hike
  graph.encoded_values: road_class,road_class_link,road_environment,max_speed,road_access,track_type,surface
  graph.elevation.provider: srtm
  graph.elevation.cache_dir: /usr/src/app/elevation/
  graph.elevation.dataaccess: RAM_STORE
  prepare.min_network_size: 200
  graph.dataaccess.default_type: RAM_STORE
  
server:
  application_connectors:
  - type: http
    port: 8989    bind_host: localhost
  request_log:
      appenders: []
  admin_connectors:
  - type: http
    port: 8990
    bind_host: localhostlogging:
  appenders:
  - type: file
    time_zone: UTC
    current_log_filename: logs/graphhopper.log
    log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    archive: true
    archived_log_filename_pattern: ./logs/graphhopper-%d.log.gz
    archived_file_count: 30
    never_block: true
  - type: console
    time_zone: UTC
    log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    ```

https://github.com/helpbuttons/helpbuttons/tree/graphhopper
